#!/bin/bash
# $IMAGE_NAME var is injected into the build so the tag is correct. 
# SOURCE_BRANCH: the name of the branch or the tag that is currently being tested.
# SOURCE_COMMIT: the SHA1 hash of the commit being tested.
# COMMIT_MSG: the message from the commit being tested and built.
# DOCKER_REPO: the name of the Docker repository being built.
# DOCKER_TAG: the Docker repository tag being built.
# IMAGE_NAME: the name and tag of the Docker repository being built. (This variable is a combination of DOCKER_REPO:DOCKER_TAG.)

echo $SOURCE_BRANCH
echo $SOURCE_COMMIT
echo $COMMIT_MSG
echo $DOCKER_REPO
echo $DOCKER_TAG

docker build --build-arg VCS_REF=`git rev-parse — short HEAD` \
  --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
  --build-arg VERISON=0.1.0+sha`git rev-parse — short HEAD` \
  -t $IMAGE_NAME .